language: java
jdk:
  -openjdk11

branches:
  only:
    - master

#Travis Ci 서버의 홈
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

notifications:
  email:
    recipients:
      -"dnrgnl2718@gmail.com"
